# -*- coding: utf-8 -*-

COMPRESS_LEVEL_FAST = 1
COMPRESS_LEVEL_TRADEOFF = 6
COMPRESS_LEVEL_BEST = 9

DEFAULT_PICKLE_PROTOCOL_VERSION = 5
DEFAULT_PICKLE_ENCODING = "ASCII"

DISABLE_ORJSON_INSTALL_ENV_NAME = "TYPE_SERIALIZE_DISABLE_ORJSON_INSTALL"
