# -*- coding: utf-8 -*-

from typing import Final

COMPRESS_LEVEL_FAST: Final[int] = 1
COMPRESS_LEVEL_TRADEOFF: Final[int] = 6
COMPRESS_LEVEL_BEST: Final[int] = 9

DEFAULT_PICKLE_PROTOCOL_VERSION: Final[int] = 5
DEFAULT_PICKLE_ENCODING: Final[str] = "ASCII"

DISABLE_ORJSON_INSTALL_ENV_NAME: Final[str] = "TYPE_SERIALIZE_DISABLE_ORJSON_INSTALL"
